/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_spp;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class MenuUtama extends javax.swing.JFrame {
    private String level;
    public void setLevel(String a){
        level=a;
        if(level.equals("admin")){
        }else if(level.equals("petugas")){
            mn_master.hide();
            mn_laporan.hide();
        }else if(level.equals("siswa")){
            mn_transaksi.hide();
            mn_master.hide();
            mn_laporan.hide();
        }else{
            JOptionPane.showMessageDialog(null, "Level tidak ditemukan!");
        }
    }

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_logout = new javax.swing.JMenuItem();
        mn_master = new javax.swing.JMenu();
        mn_datasiswa = new javax.swing.JMenuItem();
        mn_datapetugas = new javax.swing.JMenuItem();
        mn_datakelas = new javax.swing.JMenuItem();
        mn_dataspp = new javax.swing.JMenuItem();
        mn_bayar = new javax.swing.JMenu();
        mn_transaksi = new javax.swing.JMenuItem();
        mn_history = new javax.swing.JMenuItem();
        mn_laporan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_spp/pembayaran (1) (1).jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 390);

        jMenu1.setText("Login");

        mn_logout.setText("Logout");
        mn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_logoutActionPerformed(evt);
            }
        });
        jMenu1.add(mn_logout);

        jMenuBar1.add(jMenu1);

        mn_master.setText("Master Data");

        mn_datasiswa.setText("Data Siswa");
        mn_datasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datasiswaActionPerformed(evt);
            }
        });
        mn_master.add(mn_datasiswa);

        mn_datapetugas.setText("Data Petugas");
        mn_datapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datapetugasActionPerformed(evt);
            }
        });
        mn_master.add(mn_datapetugas);

        mn_datakelas.setText("Data Kelas");
        mn_datakelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datakelasActionPerformed(evt);
            }
        });
        mn_master.add(mn_datakelas);

        mn_dataspp.setText("Data SPP");
        mn_dataspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_datasppActionPerformed(evt);
            }
        });
        mn_master.add(mn_dataspp);

        jMenuBar1.add(mn_master);

        mn_bayar.setText("Transaksi");

        mn_transaksi.setText("Transaksi Pembayaran");
        mn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_transaksiActionPerformed(evt);
            }
        });
        mn_bayar.add(mn_transaksi);

        mn_history.setText("History Pembayaran");
        mn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_historyActionPerformed(evt);
            }
        });
        mn_bayar.add(mn_history);

        jMenuBar1.add(mn_bayar);

        mn_laporan.setText("Laporan");
        mn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_laporanActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Laporan Transaksi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mn_laporan.add(jMenuItem1);

        jMenuBar1.add(mn_laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_datasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datasiswaActionPerformed
        // TODO add your handling code here:
        form_siswa fs = new form_siswa();
        fs.show();
        this.dispose();
        
    }//GEN-LAST:event_mn_datasiswaActionPerformed

    private void mn_datapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datapetugasActionPerformed
        // TODO add your handling code here:
        form_petugas fp = new form_petugas();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_mn_datapetugasActionPerformed

    private void mn_datakelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datakelasActionPerformed
        // TODO add your handling code here:
        form_kelas fk = new form_kelas();
        fk.show();
        this.dispose();
        
    }//GEN-LAST:event_mn_datakelasActionPerformed

    private void mn_datasppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_datasppActionPerformed
        // TODO add your handling code here:
        form_spp fs = new form_spp();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_mn_datasppActionPerformed

    private void mn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_transaksiActionPerformed
        // TODO add your handling code here:
        form_pembayaran fp = new form_pembayaran();
        fp.show();
        this.dispose();
    }//GEN-LAST:event_mn_transaksiActionPerformed

    private void mn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_logoutActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.show();
        this.dispose();
    }//GEN-LAST:event_mn_logoutActionPerformed

    private void mn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_historyActionPerformed
        // TODO add your handling code here:
        form_history fh = new form_history();
        fh.show();
        this.dispose();
    }//GEN-LAST:event_mn_historyActionPerformed

    private void mn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_laporanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        form_laporan fl = new form_laporan();
        fl.show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mn_bayar;
    private javax.swing.JMenuItem mn_datakelas;
    private javax.swing.JMenuItem mn_datapetugas;
    private javax.swing.JMenuItem mn_datasiswa;
    private javax.swing.JMenuItem mn_dataspp;
    private javax.swing.JMenuItem mn_history;
    private javax.swing.JMenu mn_laporan;
    private javax.swing.JMenuItem mn_logout;
    private javax.swing.JMenu mn_master;
    private javax.swing.JMenuItem mn_transaksi;
    // End of variables declaration//GEN-END:variables
}
